// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {system} from '../models';

export function GetChartData():Promise<Array<core.TrafficDataPoint>>;

export function GetLogs():Promise<Array<core.LogEntry>>;

export function GetStats():Promise<core.Stats>;

export function GetSystemConnections():Promise<Array<system.ConnectionInfo>>;

export function Greet(arg1:string):Promise<string>;

export function SetSystemProxy(arg1:boolean):Promise<void>;
