// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChartData() {
  return window['go']['main']['App']['GetChartData']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSystemConnections() {
  return window['go']['main']['App']['GetSystemConnections']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['main']['App']['SetSystemProxy'](arg1);
}
