// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {main} from '../models';
import {system} from '../models';

export function AddAdblockFilter(arg1:string,arg2:string):Promise<void>;

export function AddRule(arg1:string,arg2:string):Promise<void>;

export function DeleteAdblockFilter(arg1:string):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function EnableAdblock(arg1:boolean):Promise<void>;

export function EnableProtection(arg1:boolean):Promise<void>;

export function GetAdblockFilters():Promise<Array<core.AdblockFilter>>;

export function GetAdblockStatus():Promise<boolean>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetAppSettings():Promise<main.AppSettings>;

export function GetChartData(arg1:string):Promise<Array<core.TrafficDataPoint>>;

export function GetLogs():Promise<Array<core.LogEntry>>;

export function GetLogsPaginated(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<core.PaginatedLogs>;

export function GetProtectionStatus():Promise<boolean>;

export function GetRules():Promise<Array<core.Rule>>;

export function GetRulesPaginated(arg1:number,arg2:number,arg3:string):Promise<core.PaginatedRulesResponse>;

export function GetStartupStatus():Promise<boolean>;

export function GetStats():Promise<core.Stats>;

export function GetSystemConnections():Promise<Array<system.ConnectionInfo>>;

export function Greet(arg1:string):Promise<string>;

export function RefreshAdblockFilters():Promise<void>;

export function SaveAppSettings(arg1:main.AppSettings):Promise<void>;

export function SetRunOnStartup(arg1:boolean):Promise<void>;

export function SetSystemProxy(arg1:boolean):Promise<void>;

export function ToggleAdblockFilter(arg1:string,arg2:boolean):Promise<void>;

export function ToggleRule(arg1:string,arg2:boolean):Promise<void>;
