// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2) {
  return window['go']['main']['App']['AddRule'](arg1, arg2);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function EnableProtection(arg1) {
  return window['go']['main']['App']['EnableProtection'](arg1);
}

export function GetChartData() {
  return window['go']['main']['App']['GetChartData']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetProtectionStatus() {
  return window['go']['main']['App']['GetProtectionStatus']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetRulesPaginated(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRulesPaginated'](arg1, arg2, arg3);
}

export function GetStartupStatus() {
  return window['go']['main']['App']['GetStartupStatus']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetSystemConnections() {
  return window['go']['main']['App']['GetSystemConnections']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetRunOnStartup(arg1) {
  return window['go']['main']['App']['SetRunOnStartup'](arg1);
}

export function SetSystemProxy(arg1) {
  return window['go']['main']['App']['SetSystemProxy'](arg1);
}

export function ToggleRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleRule'](arg1, arg2);
}
